### ISSUE TITLE
support avif-sequence

### ISSUE THREAD

**Issue by Coro365** [xiaozhuai/imageinfo-rs#3]
This crate is compatible with avif, which is very helpful.
Thank you.
However, it seems that avif-sequence (avis) is not supported.
It would be helpful if you could help me.

### xxd
```
xxd ~/5770067387.avif | grep avis
00000000: 0000 002c 6674 7970 6176 6973 0000 0000  ...,ftypavis....
00000010: 6176 6973 6176 6966 6d73 6631 6973 6f38  avisavifmsf1iso8
```

### test data
- [5770067387.zip](https://github.com/xiaozhuai/imageinfo-rs/files/12368265/5770067387.zip)
- source: "[IMG_1322](https://www.flickr.com/photos/srahn/5770067387/)"  by [Stephen Rahn](https://www.flickr.com/photos/srahn/) is licensed under CC0 1.0

Thank you!

**Comment by xiaozhuai** [comment]
@Coro365 
Is avis contains sequence frames, like webp?

**Comment by Coro365** [comment]
Yes.
This article contains examples.

https://blog.coro3.net/av1-avif-avis-quick-review/#avis-avif-sequences-from-mp4

**Comment by xiaozhuai** [comment]
@Coro365 
I've release 0.7.8 just now.
Please install 0.7.8 to see if it works or not.

**Comment by Coro365** [comment]
Wow! thank you!
I didn't expect it to work so quickly.

I'm surprised it doesn't take more than 30 minutes.
I was prepared for about 3 months.

Updated to 0.7.8 and confirmed it works with avis.

very very thank you!

**Comment by xiaozhuai** [comment]
@Coro365 
You are welcome. Glad to hear that imageinfo-rs is helpful for you.
Since this issue is solved, I'm going to close it as completed.
Feel free to reopen if you'd like to discuss further.

**Comment by xiaozhuai** [comment]
@Coro365 
BTW, I use the image you provide for test usage. 
If you don't want that, I'll remove it from the library.

**Comment by Coro365** [comment]
It is not my shot, but it is CC0 (Public domain), so I think it is OK.
https://www.flickr.com/photos/srahn/5770067387/

Thanks for your concern.
