### ISSUE TITLE
BigTiff

### ISSUE THREAD

**Issue by jayvdb** [xiaozhuai/imageinfo-rs#5]
Just a note that the TIFF support here doesnt support BigTiff http://bigtiff.org/ . The tiff crate does support bigtiff for anyone interested in trying to support it
[github.com/search?q=repo%3Aimage-rs%2Fimage-tiff%20bigtiff&type=code](https://github.com/search?q=repo%3Aimage-rs%2Fimage-tiff%20bigtiff&type=code)

**Comment by xiaozhuai** [comment]
Thanks for the note, investigating now.

**Comment by xiaozhuai** [comment]
Hello @jayvdb , I found this in the http://bigtiff.org/ page.

> Please note this is not an official release of libtiff.  This version has been submitted for a future standard update. 

Has bigtiff been merged into the libtiff mainline?

**Comment by jayvdb** [comment]
That page is very old. 
It was added to libtiff v4.0.0 c.f. https://libtiff.gitlab.io/libtiff/specification/coverage-bigtiff.html , which I believe was 2011.

Oddly, it looks like BigTiff support was added to exiftool before that, in [2007](https://github.com/exiftool/exiftool/blob/b6d6096/Changes?rgh-link-date=2024-11-29T18%3A29%3A14Z#L8419C1-L8419C28).

**Comment by xiaozhuai** [comment]
The result of the investigation is that we can add support for bigtiff, but because imageinfo uses the `i64` type to represent width and height, bigtiff uses the `u64` type. Although this may cause potential problems for very large image files, in theory, images with width/height > INT64_MAX should not appear in reality.

**Comment by xiaozhuai** [comment]
@jayvdb Please check version 0.7.27. It should support bigtiff now.

**Comment by xiaozhuai** [comment]
Hello @jayvdb 
Please let me know if it works or not.
Thanks!

**Comment by jayvdb** [comment]
The executable is saying "unrecognised image format"
There is a test image at https://github.com/Roughsketch/imagesize/pull/43 , and some in https://github.com/image-rs/image-tiff/tree/master/tests/images/bigtiff

**Comment by jayvdb** [comment]
oh ... hang on .. I didnt pull main

**Comment by jayvdb** [comment]
Ok, now I have the latest, yup it is working well.  Thank you!!
